nix-community/nix-eval-jobs

flake.nix
src/hydra-eval-jobs.cc

While the current output may be sufficient for Hydra it's not enough for a more generically useful evaluator.
The encoding method isn't the most computationally efficient (it does a double encode/decode) but it was the way I could figure out how to do so without replicating code from the Nix code base.

Add full meta to output

---

src/nix-eval-jobs.cc
tests/test_eval.py

I removed meta from the output in https://github.com/nix-community/nix-eval-jobs/commit/434376f8e1ef653e79b4c2b5a38cba45109152e4 with the intention of adding it back gated by a flag, but that never happened.
Adding meta is quite a substantial increase in output size and has some non-trivial performance impact at scale, so it's best to leave it as opt-in.

Add flag to enable meta

---

.github/workflows/update-flake-lock.yml

I have no idea if this actually works without the token. Hopefully it will.

Add github action to auto-update flake.lock

---

.github/workflows/update-flake-lock.yml

I think this _might_ fix the issue where ci is not running on auto-update PRs?
See https://github.com/nix-community/nix-eval-jobs/pull/22.

Enable github token in auto-update workflow

---

src/nix-eval-jobs.cc

The default buffering behavior depends on whether the output is connected to an interactive device. This causes output lines to be buffered in an undesirable way when stdout is piped, which is how nix-eval-jobs is normally used. Let's fix it by flushing stdout explicitly.
You can reproduce the issue with the expression below. Try the following from an interactive terminal:
1. `nix-eval-jobs buffer-repro.nix`
2. `nix-eval-jobs buffer-repro.nix | cat`
3. `stdbuf -oL nix-eval-jobs buffer-repro.nix | cat`
4. Apply the patch, then `nix-eval-jobs buffer-repro.nix | cat`
```nix
let
nixpkgs = builtins.fetchTarball {
url = "https://github.com/NixOS/nixpkgs/archive/554d2d8aa25b6e583575459c297ec23750adb6cb.tar.gz";
sha256 = "01yfqslnkyrfb5yjfablhvw830iw0za3mab4n03a0ldyq5ac6wh1";
};
pkgs = import …
```

Flush cout after each output line

---

src/nix-eval-jobs.cc

To avoid `Collecting from unknown thread`.  I think this is a reasonable change, since `nix-eval-jobs`' hack is to basically replace the nix garbage collector with the operating system.
Closes #47

Set GC_DONT_GC=1.

---

src/nix-eval-jobs.cc

The args struct is statically allocated, so `-Wnon-virtual-dtor` is just noise.

Ignore -Wnon-virtual-dtor for static struct.

---

shell.nix

I found debugging in gdb critical when debugging some issues.

Add debug symbols to nix-shell.

---

src/nix-eval-jobs.cc

Using nix' `Pid` type and a `Proc` struct to group together fds and pids to auto-cleanup resources. This should help avoid hitting maximum `nproc`s too soon.
This also simplifies `main`.

Kill zombies.

---

tests/assets/ci.nix
tests/assets/flake.nix
tests/test_eval.py

I noticed that this was broken in https://github.com/nix-community/nix-eval-jobs/pull/43 but was not tested.

Add test for a job with a nested attrset

---

src/nix-eval-jobs.cc
tests/assets/ci.nix
tests/test_eval.py

This will respect `recurseForDerivations` when iterating over attrsets.
Example expression:
``` nix
{ system ? builtins.currentSystem }:
{
topDrv = derivation {
inherit system;
name = "drvTop";
builder = ":";
};
drvA = derivation {
inherit system;
name = "drvA";
builder = ":";
};
recurse = {
drvB = derivation {
inherit system;
name = "drvA";
builder = ":";
};
};
}
```
Closes #9

Add support for recurseForDerivations

---

src/nix-eval-jobs.cc
tests/assets/ci.nix
tests/test_eval.py

This ensures correct handling of attrnames with a dot in them and will
not throw errors about illegal attrnames.
Additionally this escapes any attributes containing dots in the JSON
output and adds another field called `attrPath` which contains the
attribute path as a list.
Example output:
``` json
{
"attr": "hello",
"attrPath": [
"hello"
],
"drvPath": "/nix/store/n204jib73z55cp9s0rmw1c5v5q528j7v-hello-2.12.drv",
"name": "hello-2.12",
"outputs": {
"out": "/nix/store/h59dfk7dwrn7d2csykh9z9xm2miqmrnz-hello-2.12"
},
"system": "x86_64-linux"
}
```

Replace internal attr string representation with an array

---

flake.lock

flake.lock: Bump flake inputs

---

src/nix-eval-jobs.cc
tests/test_eval.py

This PR adds support for passing a Nix expression on the command line (`--expr` / `-E`). It's done following the same semantics as in `nix-instantiate`, where `--expr` / `-E` is [a valueless flag](https://github.com/NixOS/nix/blob/af4e8b00fb986acf32d7e4cd4fff7218b38958df/src/nix-instantiate/nix-instantiate.cc#L185-L187) that causes the positional "file" arguments to be interpreted as Nix expressions rather than paths. Closes #38.
Also tacking on a small change to not touch `evalSettings.pureEval` unless `--impure` or `--flake` is specified. This allows eval flags like `--pure-eval` to be used.

Add support for passing a Nix expression on the command line

---

src/nix-eval-jobs.cc

This can be useful when you are not in control over your expressions.
My use case is evaluating a Hydra jobset.

Add parameter to force recursion (don't honour recurseIntoAttrs)

---

src/nix-eval-jobs.cc

Fixes: https://github.com/nix-community/nix-eval-jobs/issues/156

fix: catch errors for invalid derivations

---

src/nix-eval-jobs.cc

Fixes #205 
`nix-eval-jobs` should not try to evaluate `recurseForDerivations` in `force-recurse` mode.

fix recurseForDerivations evaluation in force-recurse mode

---

.clang-format
default.nix
flake.nix
src/nix-eval-jobs.cc
treefmt.toml

This patch adds the `--override-input` flags as present in the nix CLI, closing #144.
A more complete implementation would have been adding `MixFlakeOptions` to `MyArgs` parents but I am not too familiar with the codebase and I opted for the simpler solution of adding the single flag.
I allowed myself to readjust the flake adding a derivation based on clangStdenv, but I can remove that commit from the PR if undesidered.
Thank you!

Add flake --override-input

---

.github/workflows/nix-github-actions.yml
LICENSE.md
README.md
dev/treefmt.nix
src/nix-eval-jobs.cc

writeLine will throw a SysError exception, which obfuscates out-of-memory events where the eval worker is killed by the OS. readLine is suffering from the same problem and will be handled in a subsequent commit.

handle broken evaluation worker pipes more gracefully

---

src/nix-eval-jobs.cc

This error handling was copied by accident in https://github.com/nix-community/nix-eval-jobs/commit/5c764d4a67feceae1848414fd9434e79120884e6#diff-a79ded172fd76747492a417a39848b6c25c14238e65971e6a05fe81706d5048fR622

don't fail nix-eval-jobs on eval errors

---

README.md
src/drv.cc
src/drv.hh

- fixes the regression introduced in https://github.com/nix-community/nix-eval-jobs/pull/304
I also took the chance to fix the spelling of `notBuild` to `notBuilt` (I suspect this is not a breaking change since `nix-eval-jobs` hasn't been released since, and the release would have been broken anyway)

fix: cacheStatus

---

src/eval-args.cc

Tested on my dotfiles which have two lock files.

Add `--reference-lock-file` option

---

src/drv.cc

before we would disable output path for all derivations, now we just do this for CA derivations.

improve compatibility if ca derivations are present

---

default.nix

Allows for passing the git version of `n-e-j` into `n-f-b` like so:
```nix
(pkgs.callPackage inputs.nix-fast-build.packages.${pkgs.stdenv.system}.nix-fast-build.override {
nix-eval-jobs = inputs.nix-eval-jobs.packages.${pkgs.stdenv.system}.nix-eval-jobs;
})
```

Passthrough `nix`

---

src/drv.cc

Hack until https://github.com/NixOS/nix/issues/11885 is resolved.
---
~~I'll test in the Hydra PR in a moment.~~ Hydra build locally. https://github.com/NixOS/hydra/pull/1421 should pass shortly too.

Make fallback logic for CA derivations more flexible

---

flake.nix
src/drv.cc
src/drv.hh
src/eval-args.cc
src/eval-args.hh
src/nix-eval-jobs.cc
src/worker.cc
tests/assets/flake.nix
tests/test_eval.py

This is a commit from @ma27 https://git.lix.systems/ma27/nix-eval-jobs/commit/5ce92e2c4d318b30edaafa4d8664b9e15e941f32 I rebased. Thanks @ma27!
This (or something like it) is needed for `nix-eval-jobs` to replace `hydra-eval-jobs`.
----------
The part about finding `_hydraAggregate`/`constituents` is basically derived from `hydra-eval-jobs`, however the part about `namedConstituents` has been changed: we still stream out jobs when they appear, however we suppress this for aggregate jobs.
These jobs are post-processed at the end, i.e. if `namedConstituents` exist, these will be mapped to the drvPath of the other jobs. Then, the drv will be rewritten to contain the drvPath of said jobs[1] and the JSON containing the rewritten `drvPath` will be printed out.
[1] This was an optimization to …

Bring back constituents to Hydra

---

src/nix-eval-jobs.cc
src/worker.cc
tests/test_eval.py

@Ma27 I minimized the bug! But I am trouble figuring out why it is happening.

Test aggregates more

---

.clang-tidy
src/drv.cc
src/drv.hh
src/eval-args.cc
src/eval-args.hh
tests/assets/ci.nix
tests/assets/flake.lock
tests/test_eval.py

This allows for more interesting build scheduling.

expose required builds and substitutes

---

README.md
src/eval-args.cc
src/eval-args.hh
src/worker.cc
tests/test_eval.py

Allow applying every eval'ed drv to a provided nix expression to evaluate arbitrary fields.
EXAMPLE
```
% ./result/bin/nix-eval-jobs --flake github:NixOS/patchelf#hydraJobs \
--apply \
'drv: {
version = if drv ? version then drv.version else null;
}'
warning: `--gc-roots-dir' not specified
{"attr":"coverage","attrPath":["coverage"],"version":null}
{"attr":"patchelf-win32","attrPath":["patchelf-win32"],"version":"0.18.0"}
{"attr":"patchelf-win64","attrPath":["patchelf-win64"],"version":"0.18.0"}
{"attr":"release","attrPath":["release"],"version":null}
{"attr":"tarball","attrPath":["tarball"],"version":"0.18.0"}
```

feat: add `--apply` flag

---

src/nix-eval-jobs.cc

Output lines of differents thread can be intertwined. Granting mutual access to `std::cout` fixes this.

fix concurrency bug by locking cout

---

src/nix-eval-jobs.cc

Prevent misuse of function because it moves `*this`.

mark member function to be called on rvalue

---

src/nix-eval-jobs.cc

this has no effect and it should be up to the user to decide if they want restrict-eval or not.

no longer override restrict-eval
